### ISSUE TITLE
After Imagine, occasionally the response does not include the new chat message.

### ISSUE THREAD

**Issue by Swennet** [eDiasoft/midjourney-api-php#1]
First off, I want to say this is a great library to use, thanks for making it!

I've noticed that quite often, and seemingly randomly, the response returned by Imagine does not contain the recently generated image. In this case it seems that it shows older messages from the same channel.

Is this a bug or do I have something wrongly configured?

**Comment by ShuCh3n** [comment]
Can you describe the exact step you take? Each Imagine action contains a unique set of strings, based on that string I retrieve the image.

**Comment by Swennet** [comment]
@ShuCh3n I'm using the ChatGPT API to generate Midjourney prompts for a bunch of horror stories, so some of the prompts end up containing "banned" keywords such as "blood". These normally show an "Action needed to continue" warning instead of the generated images.

However, I now realise that Midjourney was generating some of these prompts without any warnings - even showing the result - and then immediately deleting the resulting message after the generation was complete.

This didn't reflect on my Discord channel window until I reloaded the applicaton, adding to my confusion.

So this isn't an issue with your package, but an issue with Midjourney's warning system letting some prompts go through before deciding to delete the results.
