### ISSUE TITLE
Can't retrieve Guild ID.

### ISSUE THREAD

**Issue by adas-hitpromo** [eDiasoft/midjourney-api-php#5]
![image](https://github.com/eDiasoft/midjourney-api-php/assets/132877231/ae64ea4d-f9e8-48a2-94de-c9b486198f1f)

This is the issue that i am getting even after putting all the information correctly

**Comment by ShuCh3n** [comment]
Probably your channel id is incorrect.

**Comment by ShuCh3n** [comment]
I hope your issue is fixed.

**Comment by taytus** [comment]
I'm having the same issue. The channeID and token are correct (tested with another library)

Same error

**Comment by ryanatearth** [comment]
I just downloaded the library to try to use it and having the same error.

**Comment by ShuCh3n** [comment]
Did you follow the Readme to get the correct channel_id?

**Comment by ryanatearth** [comment]
Yes I did.  As with another comment, I have tested this with another library and it was working.  So seems like this is an issue.  Be happy to provide any other information.

**Comment by albrox** [comment]
this seems not solved?

**Comment by ShuCh3n** [comment]
Check the channel_id, most of the time this is the issue
