### ISSUE TITLE
Gateway Timeout errors

### ISSUE THREAD

**Issue by interaxive** [eDiasoft/midjourney-api-php#7]
I installed everything successfully but am getting Gateway Timeout errors each time.  Is there some way to get the job id before, or while, the job is processed?

Also, the email address provided for contact is apparently not active.

**Comment by ShuCh3n** [comment]
Are you using guzzle?

Also please check your discord history to see what happened to your request. Sometimes when the result is inappropriate (NSFW or violence) the message will get hidden. That will result in a timeout.

```php
$midjourney = new MidjourneyApiClient($channel_id, $authorization);
$midjourney->imagine('Elephant and a snake romantically having a diner');

print($midjourney->interactionId()); //To get your job ID

```

Ps.
The email works now :) thanks for mentioning it.

**Comment by interaxive** [comment]
Yes, I am using Guzzle, and the text prompt provided in your example, though I removed the word "romantically" just in case.  I continue to receive the same error every time, and don't see anything in my Discord history.

Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.

**Comment by ShuCh3n** [comment]
So if you don't see any chat in your discord after you executed the prompt then probably your Authorization key isn't valid
