### ISSUE TITLE
Max tries exceeded, increase the max try attempt ($midjourney->imagine(*)->setMaxRetries(30)) or check your discord what went wrong.

### ISSUE THREAD

**Issue by savani222** [eDiasoft/midjourney-api-php#8]
![image](https://github.com/eDiasoft/midjourney-api-php/assets/76660665/23b377ff-d278-46a6-a376-debb3a08feda)

**Comment by ShuCh3n** [comment]
Have you check what went wrong in your discord?

**Comment by savani222** [comment]
Yes, all okay in discord.
Because my discord account is working well in using other php package.

**Comment by ShuCh3n** [comment]
Alright, im not sure why is not working for you. Maybe you try to imagine *  ??

Replace * with a valid prompt
