### ISSUE TITLE
Seems this method is down

### ISSUE THREAD

**Issue by Porcaro0** [eDiasoft/midjourney-api-php#9]
Hi there,

Having problems in using your library since few days.
Uncaught eDiasoft\Midjourney\Exceptions\MidjourneyException: Can't retrieve Guild ID.

Are you facing the same issue ?

Thanks

**Comment by ShuCh3n** [comment]
Can you provide more info? Sample code

**Comment by Porcaro0** [comment]
The problem seems to be guid retrieval

use eDiasoft\Midjourney\MidjourneyApiClient;

$channel_id = XXXXXXXXXXXXX;
$authorization = "YYYYYYYYYYYYYYYYYYYY";
$midjourney = new MidjourneyApiClient($channel_id, $authorization);
$result = $midjourney->imagine('Elephant and a snake romantically having a diner')->send();
echo $result;

Uncaught eDiasoft\Midjourney\Exceptions\MidjourneyException: Can't retrieve Guild ID. in vendor/ediasoft/midjourney-api-php/src/Config/Config.php:43 Stack trace: #0 vendor/ediasoft/midjourney-api-php/src/Commands/BaseCommand.php(38): eDiasoft\Midjourney\Config\Config->guildId() #1 vendor/ediasoft/midjourney-api-php/src/Commands/BaseCommand.php(30): eDiasoft\Midjourney\Commands\BaseCommand->defaultPayload() #2 vendor/ediasoft/midjourney-api-php/src/MidjourneyApiClient.php(22): eDiasoft\Midjourney\Commands\BaseCommand->__construct(Object(eDiasoft\Midjourney\Config\DefaultConfig), 'Elephant and a ...') #3 testmidjourney.php(43): eDiasoft\Midjourney\MidjourneyApiClient->imagine('Elephant and a ...') #4 {main} thrown in vendor/ediasoft/midjourney-api-php/src/Config/Config.php on line 43

**Comment by dvector87** [comment]
I get same issue...

**Comment by AbedRabaia** [comment]
Same issue here too @ShuCh3n  can you help

**Comment by ShuCh3n** [comment]
Looking into it

**Comment by ShuCh3n** [comment]
Can you guys confirm if the latest version fix your problems?

https://github.com/eDiasoft/midjourney-api-php/releases/tag/1.1.1

**Comment by dvector87** [comment]
same issue, Can't retrieve Guild ID.

**Comment by ShuCh3n** [comment]
Then you're setting the wrong channel ID

**Comment by dvector87** [comment]
All work perfect now, thanks
